I'm sorry, but an uncaught exception occurred.

While running game code:
  File "day1/base.rpy", line 2, in script
    call screen calendar_day1 with fade
renpy.display.screen.ScreenNotFound: Screen 'calendar_day1' is not known.

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "day1/base.rpy", line 2, in script
    call screen calendar_day1 with fade
  File "renpy/ast.py", line 2231, in execute
    self.call("execute")
    ~~~~~~~~~^^^^^^^^^^^
  File "renpy/ast.py", line 2195, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/statements.py", line 379, in call
    return method(parsed, *args, **kwargs)
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/common/000statements.rpy", line 695, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/exports/statementexports.py", line 334, in call_screen
    renpy.exports.show_screen(_screen_name, *args, _transient=True, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/screen.py", line 1355, in show_screen
    raise ScreenNotFound(name[0])
renpy.display.screen.ScreenNotFound: Screen 'calendar_day1' is not known.

Linux-6.15.8-arch1-1-x86_64-with-glibc2.41 x86_64
Ren'Py 8.4.1.25072401
 
Mon Jul 28 00:48:21 2025
